import "./globals.css";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Diamond Nails & Spa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
